### ISSUE TITLE
Update the README.md file

### ISSUE THREAD

**Issue by dpkreativ** [Community-OSS/gdg-aba-website-frontend#1]
The README.md file for this repo should comprehensively describe the project and provide links to the relevant resources on the project.

## Acceptance criteria
It should have the following:
- A description of what we're working on (The GDG Aba Website)
- Our stack
- Links to Contributing and Code of Conduct files
- Link to the Figma file containing the design (Screenshot included)

**Comment by KrownWealth** [comment]
Hi there,

I would like to work on this issue, I have prior(beginner) experience creating React application.

**Comment by dpkreativ** [comment]
Hi @KrownWealth thanks for indicating interest in working on this issue.

Please exercise some patience while we do some mild cleanup of the repo, then this issue may be assigned to you.

**Comment by KrownWealth** [comment]
Alright

**Comment by dpkreativ** [comment]
https://www.figma.com/proto/QZ3HbsJlTJ67o2uhCPFo9w/GDG-Aba?page-id=81%3A925&type=design&node-id=81-926&viewport=1270%2C873%2C0.27&scaling=min-zoom&starting-point-node-id=81%3A926

Design file

**Comment by KrownWealth** [comment]
It will be a great pleasure to work with you guys.
