### ISSUE TITLE
Create Contributing guide

### ISSUE THREAD

**Issue by dpkreativ** [Community-OSS/gdg-aba-website-frontend#3]
We need a guide that shows new and existing contributors how to contribute to the project.

It should at least have the following:
- A complete breakdown of the stack
- A step-by-step guide to contributing
- Some caveats where necessary
- Bonus points if the tone of the contributing guide sounds like a friendly letter

**Comment by KrownWealth** [comment]
It will be a great priviledge to contribute to this amazing projects. I can update the README file alongside create a contributing guide for this project.

**Comment by dpkreativ** [comment]
Thank you. We will get back to you on this shortly. Thanks

**Comment by dpkreativ** [comment]
@KrownWealth join our Slack to keep updated on conversations around this. Thanks

https://join.slack.com/t/gdgaba/shared_invite/zt-1wewkw2c6-fnRLc9T7XCSoiIrOtTGNcQ
